name: Deploy to WP Engine

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SSH Deploy to WP Engine
        uses: bowiedev/github-action-wpengine-ssh-deploy@master
        env:
          WPE_ENV_NAME: githubpipestg
          WPE_SSHG_KEY_PUBLIC: ${{ secrets.WPENGINE_DEPLOY_PUBLIC_KEY }}
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_DEPLOY_PRIVATE_KEY }}
          TPO_SRC_PATH: ""
          TPO_PATH: ""
